version: "3.7"
services:
    nginx:
        image: nginx:latest
        container_name: web-server
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - cookbooks
    app:
        build: .
        container_name: cookbookshq
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - cookbooks
    db:
        image: mariadb:latest
        container_name: db
        environment:
            MYSQL_DATABASE: cookbooks
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - cookbooks
    cache:
        image: redis:latest
        container_name: cache
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
volumes:
    mysqldata:
    cache:
        driver: local

networks:
    cookbooks:
        driver: bridge
