name: StyleCheck

on:
    push:
        branches: [ "develop", "staging" ]
    pull_request:
        branches: [ "develop", "staging" ]

jobs:
    php-cs:
        runs-on: ubuntu-latest
        steps:
            -   uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
                with:
                    php-version: '8.0'
            -   uses: actions/checkout@v3
            -   name: Check Arkitectural rules
                run: echo "checking rules"
