name: Run Static analysis

on:
    push:
        branches: [ "master", "develop", "staging" ]
    pull_request:
        branches: [ "master", "develop", "staging" ]

jobs:
    php-cs:
        runs-on: ubuntu-latest
        steps:
            -   uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
                with:
                    php-version: '8.2'
            -   uses: actions/checkout@v3
            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   name: Running static analysis
                run: vendor/bin/phpstan analyse --memory-limit=2G
